### ISSUE TITLE
Error in on_message when bot needs to make request to course explorer

### ISSUE THREAD

**Issue by timot3** [timot3/uiuc-classes-bot#6]
```Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\timot\projects\misc\discord\uiuc-classes-bot\venv\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:/Users/timot/projects/misc/discord/uiuc-classes-bot/bot.py", line 58, in on_message
    await send_class(message.channel, course)
  File "C:\Users\timot\projects\misc\discord\uiuc-classes-bot\utils\functions.py", line 99, in send_class
    await channel.send(embed=message_str.get_embed())
  File "C:\Users\timot\projects\misc\discord\uiuc-classes-bot\venv\lib\site-packages\discord\abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\timot\projects\misc\discord\uiuc-classes-bot\venv\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.2.value: This field is required```

Maybe an issue with message length?

**Comment by timot3** [comment]
Nevermind, it was a problem with positional arguments in the Class constructor.
